test_heapsort: test_heapsort.c ../base.c ../heap.c ../include/base.h
	gcc test_heapsort.c ../base.c ../heap.c -I ../include/ -o ../build/test_heapsort

get_string: get_string.c ../string.c ../include/io.h
	gcc get_string.c ../string.c -I ../include/ -o ../build/get_string
